<?php 

function move_user_user_cancel_methods_alter(&$methods) {
  unset($methods['user_cancel_reassign']);
  $methods['move_user_reassign'] = array(
    'title' => t('Disable the account and make its content belong to another user.'),
    'description' => t('All your content will be removed and assigned to a different user'),
    'access' => \Drupal::currentUser()->hasPermission('administer users'),
  );
}

function move_user_form_alter(&$form, \Drupal\Core\Form\FormStateInterface &$form_state, $form_id) {
  if ($form_id == 'user_cancel_confirm_form' || $form_id == 'user_multiple_cancel_confirm_form') { 
    // @FIXME
// // @FIXME
// // This looks like another module's variable. You'll need to rewrite this call
// // to ensure that it uses the correct configuration object.
// $form['reassign_user'] = array(
//       '#type' => 'textfield',
//       '#title' => t('Reassign content to:'),
//       '#maxlength' => 60,
//       '#autocomplete_path' => 'user/autocomplete',
//       '#weight' => 10,
//       '#description' => t('Leave blank for %anonymous.',
//         array('%anonymous' => variable_get('anonymous', t('Anonymous')))),
//     );

  }
}

function move_user_user_cancel($edit, $account, $method) {
  $new_account = user_load_by_name($edit['reassign_user']);
  $new_uid = !empty($new_account->uid) ? $new_account->uid : 0;
  switch ($method) {
    case 'move_user_reassign':

      module_load_include('inc', 'node', 'node.admin');
      $nodes = db_select('node', 'n')
        ->fields('n', array('nid'))
        ->condition('uid', $account->uid)
        ->execute()
        ->fetchCol();
      node_mass_update($nodes, array('uid' => $new_uid));

      db_update('node_revision')
        ->fields(array('uid' => $new_uid))
        ->condition('uid', $account->uid)
        ->execute();

      break;
  }
}