<?php 

/**
 * Implement of hook_user_cancel_menthods_alter().
 */
function move_user_user_cancel_methods_alter(&$methods) {
  unset($methods['user_cancel_reassign']);
  // Add a custom move user reassign method.
  $methods['move_user_reassign'] = array(
    'title' => t('Disable the account and make its content belong to another user.'),
    'description' => t('All your content will be removed and assigned to a different user'),
    'access' => \Drupal::currentUser()->hasPermission('administer users'),
  );
}

function move_user_form_alter(&$form, \Drupal\Core\Form\FormStateInterface &$form_state, $form_id) {
  if ($form_id == 'user_cancel_form' || $form_id == 'user_multiple_cancel_confirm') {
    $form['move_user_reassign'] = array(
      '#type' => 'entity_autocomplete',
      '#target_type' => 'user',
      '#title' => t('Reassign content to:'),
      '#maxlength' => 60,
      '#weight' => 10,
      '#description' => t('Leave blank for %anonymous.',
        array('%anonymous' => \Drupal::config('user.settings')->get('anonymous'))),
    );
  }
}

function move_user_user_cancel($edit, $account, $method) {
  $new_account = \Drupal\user\Entity\User::load();
  $new_uid = !empty($new_account->uid) ? $new_account->uid : 0;
  switch ($method) {
    case 'move_user_reassign':

      module_load_include('inc', 'node', 'node.admin');
      $nodes = db_select('node', 'n')
        ->fields('n', array('nid'))
        ->condition('uid', $account->uid)
        ->execute()
        ->fetchCol();
      node_mass_update($nodes, array('uid' => $new_uid));

      db_update('node_revision')
        ->fields(array('uid' => $new_uid))
        ->condition('uid', $account->uid)
        ->execute();

      break;
  }
}
